In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
%%time 
# %time is for a line ,%%is for a cell and time it show the info of each iteration
for _ in range(10): 
    my_arr2 = my_arr*2

Wall time: 29.9 ms


In [5]:
%%timeit 
for _ in range(10): 
    my_list2 = my_list*2

219 ms ± 4.45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


**Numpy is much faster than the raw python**

In [11]:
data = np.random.randn(2,3)
data

array([[ 0.90427054,  2.26931144,  0.4546924 ],
       [ 1.73251623, -0.70485646,  0.44507425]])

In [14]:
data_l = [6,7.5,8,0,1]
data_2 = [[1,2,3,4],[5,6,7,8]]
arr_l1=np.array(data_l)
arr_l2 = np.array(data_2)
print(arr_l1)
print(arr_l2)

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]


In [15]:
print(arr_l1.dtype)
print(arr_l2.dtype)


float64
int32


In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2,3,2))

array([[[8.52139927e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [2.22523004e-307, 3.11403376e+179]],

       [[1.39475326e-047, 4.25698887e+174],
        [5.88839956e-062, 4.42419421e-062],
        [1.81575104e-052, 1.32656610e-075]]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
int_arr=np.array([1,2,3,4,5,6])
int_arr.dtype

dtype('int32')

In [25]:
float_arr = int_arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5., 6.])

In [27]:
float_arr.dtype

dtype('float64')

In [28]:
float_arr = np.array([1.1,2.2,-3.2])
int_arr = float_arr.astype(np.int32)
int_arr

array([ 1,  2, -3])

In [29]:
str_arr = np.array(['1.233','-0.7','42'])
str_arr

array(['1.233', '-0.7', '42'], dtype='<U5')

In [31]:
str_arr = str_arr.astype(float)
str_arr

array([ 1.233, -0.7  , 42.   ])

In [32]:
str_arr-str_arr

array([0., 0., 0.])

In [33]:
str_arr*str_arr

array([1.520289e+00, 4.900000e-01, 1.764000e+03])

In [34]:
1/(str_arr+1)

array([0.44782803, 3.33333333, 0.02325581])

In [35]:
arr = np.arange(10)
arr[5]

5

In [36]:
arr[5:8]

array([5, 6, 7])

In [38]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
slice_ = arr[5:8]
slice_

array([12, 12, 12])

**slice_ = 10 will not apply 10 to the arr,only arr[5:8]=10 will make effect.**

In [42]:
slice_[1]=1233
arr

array([   0,    1,    2,    3,    4,   12, 1233,   12,    8,    9])

In [43]:
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr2d[1]

array([4, 5, 6])

In [45]:
arr2d[1,2]

6